#Task 1
Read the Population dataset from the CSV file

In [1]:
import pandas as pd

In [2]:
population = pd.read_csv('/content/population.csv')
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [ ]:
population.shape

(25, 2)

In [ ]:
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [ ]:
population.dtypes

country       object
population     int64
dtype: object

#Task 2
Read the GDP dataset from the Excel file.

Hint:

● Use the appropriate pandas function.

● Display column names and data types

In [66]:
GDP = pd.read_excel('/content/gdp.xlsx')
GDP

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [4]:
GDP.dtypes

Country    object
GDP         int64
dtype: object

In [65]:
GDP.columns

Index(['Country', 'GDP'], dtype='object')

#Task 3
Read the Internet Users dataset from the JSON file.

Hint:

● Use either the json module or pandas.

● Convert the data into a DataFrame

In [6]:
internet_users = pd.read_json('internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [7]:
internet_users = pd.read_json('internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [8]:
internet_users =pd.DataFrame(internet_users)
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

#Task 4
Read the Literacy Rate dataset from the XML file.

Hint:

● Use xml.etree.ElementTree or pandas.read_xml().

● Extract all required fields into a DataFrame.

In [10]:
data_set = pd.read_xml('/content/literacy_rate.xml')
data_set

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [11]:
data_set = pd.DataFrame(data_set)
data_set

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#Task 5    ##literacy users


Explore each dataset.

Find the following:

● Number of rows

● Number of columns

● Column names

● Data types

● Missing values

● Duplicate records

In [12]:
data_set.dtypes

name              object
literacy_rate    float64
dtype: object

In [13]:
data_set.columns

Index(['name', 'literacy_rate'], dtype='object')

In [14]:
data_set.count()

name             25
literacy_rate    25
dtype: int64

In [15]:
data_set.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [16]:

data_set.duplicated().sum()

np.int64(0)

In [17]:
len(data_set)

25

In [18]:
data_set.isnull().sum()

name             0
literacy_rate    0
dtype: int64

In [19]:
population = pd.read_csv('/content/population.csv')
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [20]:
population.dtypes

country       object
population     int64
dtype: object

In [21]:
population.columns

Index(['country', 'population'], dtype='object')

In [22]:
population.count()

country       25
population    25
dtype: int64

In [23]:
len(population)

25

In [24]:
population.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [25]:
population.isnull().sum()

country       0
population    0
dtype: int64

In [26]:
population.isna().sum()

country       0
population    0
dtype: int64

In [27]:
internet_users = pd.read_json('/content/internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [28]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [29]:
internet_users.columns

Index(['country', 'internet_users'], dtype='object')

In [30]:
internet_users.count()

country           25
internet_users    25
dtype: int64

In [35]:
internet_users.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [36]:
internet_users.isnull().sum()

country           0
internet_users    0
dtype: int64

In [33]:
len(internet_users)

25

In [34]:
internet_users.isna().sum()

country           0
internet_users    0
dtype: int64

In [37]:
GDP = pd.read_excel('/content/gdp.xlsx')
GDP

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [38]:
GDP.dtypes

Country    object
GDP         int64
dtype: object

In [125]:
GDP.columns

Index(['country', 'GDP'], dtype='object')

In [41]:
GDP.count()

Country    25
GDP        25
dtype: int64

In [39]:
GDP.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [42]:
GDP.isnull().sum()

Country    0
GDP        0
dtype: int64

In [43]:
GDP.isna().sum()

Country    0
GDP        0
dtype: int64

In [44]:
len(GDP)

25

#Task 6
Rename columns wherever necessary so that all datasets have a common column name for merging.

Hint:

● Example: Country → country

In [80]:
data_set.rename(columns={'Country':'country'},inplace = True)
data_set

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [81]:
GDP = GDP.rename(columns={"Country": "country"})
GDP

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [83]:
population.rename(columns={'Country':'country'},inplace = True)
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [84]:
internet_users.rename(columns={'Country':'country'},inplace = True)
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

#Task 7
Convert the required columns into appropriate numeric data types.

In [49]:
population['population'] = pd.to_numeric(population['population'])
population.dtypes

country       object
population     int64
dtype: object

In [51]:
internet_users['internet_users'] =pd.to_numeric(internet_users['internet_users'])
internet_users.dtypes

country           object
internet_users     int64
dtype: object

#Task 8

Merge all four datasets into one DataFrame.

Hint:

● Use the common column (country)

● Choose an appropriate join method

In [128]:
merged_df = population.merge(internet_users, on="country", how="inner")\
.merge(GDP, on="country", how="inner")\
.merge(data_set, on="country", how="inner")

In [129]:
merged_df

           country  population  internet_users       GDP  literacy_rate
0    United States   331002651       312000000  30500000           99.0
1            China  1411778724      1080000000  19230000           97.2
2            India  1380004385       850000000   4187000           77.7
3            Japan   125836021       118000000   4180000           99.0
4          Germany    83240525        79000000   4744000           99.0
5   United Kingdom    67886011        66000000   3839000           99.0
6           France    65273511        62000000   3211000           99.0
7            Italy    60461826        56000000   2420000           99.0
8           Canada    38005238        36000000   2250000           99.0
9        Australia    25687041        24000000   1880000           99.0
10          Brazil   212559417       181000000   2330000           93.2
11          Russia   145934462       125000000   2200000           99.7
12     South Korea    51780579        50000000   1800000           98.8
13           Spain    46754778        44000000   1710000           98.6
14          Mexico   128932753       102000000   1810000           95.4
15       Indonesia   273523615       212000000   1500000           96.0
16    Saudi Arabia    34813871        34000000   1100000           97.3
17          Turkey    84339067        69000000   1350000           96.7
18    South Africa    59308690        43000000    410000           95.0
19       Argentina    45195774        41000000    640000           99.1
20     Netherlands    17441139        17000000   1150000           99.0
21     Switzerland     8654622         8500000    940000           99.0
22          Sweden    10353442        10100000    650000           99.0
23          Norway     5421241         5300000    580000          100.0
24       Singapore     5850342         5600000    530000           97.5

#Task 9

Create the following calculated columns:

1. Internet Penetration (%)

2. GDP Per Capita

Hint: Round the calculated values to two decimal places

In [130]:
merged_df["internet_penetration (%)"] = (
    merged_df["internet_users"] / merged_df["population"] * 100
  ).round(2)
merged_df

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%)
0,United States,331002651,312000000,30500000,99.0,94.26
1,China,1411778724,1080000000,19230000,97.2,76.50
2,India,1380004385,850000000,4187000,77.7,61.59
3,Japan,125836021,118000000,4180000,99.0,93.77
4,Germany,83240525,79000000,4744000,99.0,94.91
5,United Kingdom,67886011,66000000,3839000,99.0,97.22
6,France,65273511,62000000,3211000,99.0,94.98
7,Italy,60461826,56000000,2420000,99.0,92.62
8,Canada,38005238,36000000,2250000,99.0,94.72
9,Australia,25687041,24000000,1880000,99.0,93.43
10,Brazil,212559417,181000000,2330000,93.2,85.15
11,Russia,145934462,125000000,2200000,99.7,85.65
12,South Korea,51780579,50000000,1800000,98.8,96.56
13,Spain,46754778,44000000,1710000,98.6,94.11
14,Mexico,128932753,102000000,1810000,95.4,79.11
15,Indonesia,273523615,212000000,1500000,96.0,77.51
16,Saudi Arabia,34813871,34000000,1100000,97.3,97.66
17,Turkey,84339067,69000000,1350000,96.7,81.81
18,South Africa,59308690,43000000,410000,95.0,72.50
19,Argentina,45195774,41000000,640000,99.1,90.72
20,Netherlands,17441139,17000000,1150000,99.0,97.47
21,Switzerland,8654622,8500000,940000,99.0,98.21
22,Sweden,10353442,10100000,650000,99.0,97.55
23,Norway,5421241,5300000,580000,100.0,97.76
24,Singapore,5850342,5600000,530000,97.5,95.72

In [131]:
merged_df['gdp_per_capita'] = (
    merged_df['GDP'] / merged_df['population']
).round(2)
merged_df

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%),gdp_per_capita
0,United States,331002651,312000000,30500000,99.0,94.26,0.09
1,China,1411778724,1080000000,19230000,97.2,76.50,0.01
2,India,1380004385,850000000,4187000,77.7,61.59,0.00
3,Japan,125836021,118000000,4180000,99.0,93.77,0.03
4,Germany,83240525,79000000,4744000,99.0,94.91,0.06
5,United Kingdom,67886011,66000000,3839000,99.0,97.22,0.06
6,France,65273511,62000000,3211000,99.0,94.98,0.05
7,Italy,60461826,56000000,2420000,99.0,92.62,0.04
8,Canada,38005238,36000000,2250000,99.0,94.72,0.06
9,Australia,25687041,24000000,1880000,99.0,93.43,0.07
10,Brazil,212559417,181000000,2330000,93.2,85.15,0.01
11,Russia,145934462,125000000,2200000,99.7,85.65,0.02
12,South Korea,51780579,50000000,1800000,98.8,96.56,0.03
13,Spain,46754778,44000000,1710000,98.6,94.11,0.04
14,Mexico,128932753,102000000,1810000,95.4,79.11,0.01
15,Indonesia,273523615,212000000,1500000,96.0,77.51,0.01
16,Saudi Arabia,34813871,34000000,1100000,97.3,97.66,0.03
17,Turkey,84339067,69000000,1350000,96.7,81.81,0.02
18,South Africa,59308690,43000000,410000,95.0,72.50,0.01
19,Argentina,45195774,41000000,640000,99.1,90.72,0.01
20,Netherlands,17441139,17000000,1150000,99.0,97.47,0.07
21,Switzerland,8654622,8500000,940000,99.0,98.21,0.11
22,Sweden,10353442,10100000,650000,99.0,97.55,0.06
23,Norway,5421241,5300000,580000,100.0,97.76,0.11
24,Singapore,5850342,5600000,530000,97.5,95.72,0.09

#Task 10

Create a SQLite database. Store the final merged dataset into a table named ‘country_statistics’

Hint:

● Use the sqlite3 library.

● Load the DataFrame using pandas.

In [193]:
import sqlite3

In [198]:
import sqlite3
conn = sqlite3.connect('country_statistics.db')
merged_df.to_sql('country_statistics',conn,if_exists='replace',index=False)
conn.close()

In [192]:
conn = sqlite3.connect('country_statistics.db')
df = pd.read_sql('select * from country_statistics',conn)
conn.close()
df

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%),gdp_per_capita
0,Switzerland,8654622,8500000,940000,99.0,98.21,0.11
1,Norway,5421241,5300000,580000,100.0,97.76,0.11
2,Singapore,5850342,5600000,530000,97.5,95.72,0.09
3,United States,331002651,312000000,30500000,99.0,94.26,0.09
4,Australia,25687041,24000000,1880000,99.0,93.43,0.07
5,Netherlands,17441139,17000000,1150000,99.0,97.47,0.07
6,Germany,83240525,79000000,4744000,99.0,94.91,0.06
7,Canada,38005238,36000000,2250000,99.0,94.72,0.06
8,United Kingdom,67886011,66000000,3839000,99.0,97.22,0.06
9,Sweden,10353442,10100000,650000,99.0,97.55,0.06
10,France,65273511,62000000,3211000,99.0,94.98,0.05
11,Spain,46754778,44000000,1710000,98.6,94.11,0.04
12,Italy,60461826,56000000,2420000,99.0,92.62,0.04
13,South Korea,51780579,50000000,1800000,98.8,96.56,0.03
14,Saudi Arabia,34813871,34000000,1100000,97.3,97.66,0.03
15,Japan,125836021,118000000,4180000,99.0,93.77,0.03
16,Turkey,84339067,69000000,1350000,96.7,81.81,0.02
17,Russia,145934462,125000000,2200000,99.7,85.65,0.02
18,China,1411778724,1080000000,19230000,97.2,76.50,0.01
19,Indonesia,273523615,212000000,1500000,96.0,77.51,0.01
20,Brazil,212559417,181000000,2330000,93.2,85.15,0.01
21,Argentina,45195774,41000000,640000,99.1,90.72,0.01
22,Mexico,128932753,102000000,1810000,95.4,79.11,0.01
23,South Africa,59308690,43000000,410000,95.0,72.50,0.01
24,India,1380004385,850000000,4187000,77.7,61.59,0.00

#Task 11

Verify that the data has been loaded successfully.

Hint: Retrieve the first five records from the SQLite table.

In [112]:
df.head()

,country,population,internet_users,literacy_rate_x,literacy_rate_y,internet_penetration (%)
0,United States,331002651,312000000,99.0,99.0,94.26
1,China,1411778724,1080000000,97.2,97.2,76.50
2,India,1380004385,850000000,77.7,77.7,61.59
3,Japan,125836021,118000000,99.0,99.0,93.77
4,Germany,83240525,79000000,99.0,99.0,94.91

#Part E – Data Analysis Using Pandas

Answer the following questions using pandas.

1 List the Top 5 countries by GDP

#

In [133]:
GDP.head()

         country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000

In [135]:
GDP = GDP.sort_values(by='GDP', ascending = False)
GDP.head(5)

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

#2 List the Top 5 countries by population

In [137]:
population = population.sort_values(by='population', ascending = False)
population.head(5)

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

#3 Calculate the average literacy rate.

In [141]:
data_set.groupby('country').mean()

                literacy_rate
country
Argentina                99.1
Australia                99.0
Brazil                   93.2
Canada                   99.0
China                    97.2
France                   99.0
Germany                  99.0
India                    77.7
Indonesia                96.0
Italy                    99.0
Japan                    99.0
Mexico                   95.4
Netherlands              99.0
Norway                  100.0
Russia                   99.7
Saudi Arabia             97.3
Singapore                97.5
South Africa             95.0
South Korea              98.8
Spain                    98.6
Sweden                   99.0
Switzerland              99.0
Turkey                   96.7
United Kingdom           99.0
United States            99.0

#4 .list all countries having a literacy rate greater than 90%

In [143]:
data_set[data_set['literacy_rate'] > 90]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#5 List all countries having an internet penetration greater than 70%.

In [151]:
merged_df[merged_df['internet_penetration (%)'] > 70]

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%),gdp_per_capita
0,United States,331002651,312000000,30500000,99.0,94.26,0.09
1,China,1411778724,1080000000,19230000,97.2,76.50,0.01
3,Japan,125836021,118000000,4180000,99.0,93.77,0.03
4,Germany,83240525,79000000,4744000,99.0,94.91,0.06
5,United Kingdom,67886011,66000000,3839000,99.0,97.22,0.06
6,France,65273511,62000000,3211000,99.0,94.98,0.05
7,Italy,60461826,56000000,2420000,99.0,92.62,0.04
8,Canada,38005238,36000000,2250000,99.0,94.72,0.06
9,Australia,25687041,24000000,1880000,99.0,93.43,0.07
10,Brazil,212559417,181000000,2330000,93.2,85.15,0.01
11,Russia,145934462,125000000,2200000,99.7,85.65,0.02
12,South Korea,51780579,50000000,1800000,98.8,96.56,0.03
13,Spain,46754778,44000000,1710000,98.6,94.11,0.04
14,Mexico,128932753,102000000,1810000,95.4,79.11,0.01
15,Indonesia,273523615,212000000,1500000,96.0,77.51,0.01
16,Saudi Arabia,34813871,34000000,1100000,97.3,97.66,0.03
17,Turkey,84339067,69000000,1350000,96.7,81.81,0.02
18,South Africa,59308690,43000000,410000,95.0,72.50,0.01
19,Argentina,45195774,41000000,640000,99.1,90.72,0.01
20,Netherlands,17441139,17000000,1150000,99.0,97.47,0.07
21,Switzerland,8654622,8500000,940000,99.0,98.21,0.11
22,Sweden,10353442,10100000,650000,99.0,97.55,0.06
23,Norway,5421241,5300000,580000,100.0,97.76,0.11
24,Singapore,5850342,5600000,530000,97.5,95.72,0.09

# 6.List the Top 5 countries by GDP per capita.

In [155]:
merged_df = merged_df.sort_values(by='gdp_per_capita', ascending = False)
merged_df

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%),gdp_per_capita
21,Switzerland,8654622,8500000,940000,99.0,98.21,0.11
23,Norway,5421241,5300000,580000,100.0,97.76,0.11
24,Singapore,5850342,5600000,530000,97.5,95.72,0.09
0,United States,331002651,312000000,30500000,99.0,94.26,0.09
9,Australia,25687041,24000000,1880000,99.0,93.43,0.07
20,Netherlands,17441139,17000000,1150000,99.0,97.47,0.07
4,Germany,83240525,79000000,4744000,99.0,94.91,0.06
8,Canada,38005238,36000000,2250000,99.0,94.72,0.06
5,United Kingdom,67886011,66000000,3839000,99.0,97.22,0.06
22,Sweden,10353442,10100000,650000,99.0,97.55,0.06
6,France,65273511,62000000,3211000,99.0,94.98,0.05
13,Spain,46754778,44000000,1710000,98.6,94.11,0.04
7,Italy,60461826,56000000,2420000,99.0,92.62,0.04
12,South Korea,51780579,50000000,1800000,98.8,96.56,0.03
16,Saudi Arabia,34813871,34000000,1100000,97.3,97.66,0.03
3,Japan,125836021,118000000,4180000,99.0,93.77,0.03
17,Turkey,84339067,69000000,1350000,96.7,81.81,0.02
11,Russia,145934462,125000000,2200000,99.7,85.65,0.02
1,China,1411778724,1080000000,19230000,97.2,76.50,0.01
15,Indonesia,273523615,212000000,1500000,96.0,77.51,0.01
10,Brazil,212559417,181000000,2330000,93.2,85.15,0.01
19,Argentina,45195774,41000000,640000,99.1,90.72,0.01
14,Mexico,128932753,102000000,1810000,95.4,79.11,0.01
18,South Africa,59308690,43000000,410000,95.0,72.50,0.01
2,India,1380004385,850000000,4187000,77.7,61.59,0.00

#7 Calculate the total population represented in the dataset.

In [156]:
merged_df['population'].sum()

np.int64(4720039725)

#8 Calculate the average internet penetration across all countries

In [157]:
merged_df['internet_penetration (%)'].mean()

np.float64(89.65960000000001)

#9 Identify the country having the highest number of internet users.

In [158]:
merged_df.loc[merged_df['internet_users'].idxmax()][['country','internet_users']]

country                China
internet_users    1080000000
Name: 1, dtype: object

#10 Find the correlation between Literacy Rate and Internet Penetration.

Hint:
 Use the appropriate pandas statistical function

In [160]:
merged_df['literacy_rate'].corr(merged_df['internet_penetration (%)'])

np.float64(0.7727975681398502)

#Part F – Data Analysis Using SQL

Answer the following questions using SQLite queries.

11 Display the Top 5 countries by GDP

In [161]:
GDP = GDP.sort_values(by='GDP', ascending = False)
GDP.head(5)

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

#12 Find the average literacy rate.

In [163]:
data_set.groupby('country').mean()

                literacy_rate
country
Argentina                99.1
Australia                99.0
Brazil                   93.2
Canada                   99.0
China                    97.2
France                   99.0
Germany                  99.0
India                    77.7
Indonesia                96.0
Italy                    99.0
Japan                    99.0
Mexico                   95.4
Netherlands              99.0
Norway                  100.0
Russia                   99.7
Saudi Arabia             97.3
Singapore                97.5
South Africa             95.0
South Korea              98.8
Spain                    98.6
Sweden                   99.0
Switzerland              99.0
Turkey                   96.7
United Kingdom           99.0
United States            99.0

#13 Display all countries having literacy rate above 90%.

In [187]:
conn = sqlite3.connect('country_statistics.db')
q = "SELECT country, literacy_rate_x FROM country_statistics WHERE literacy_rate_x > 90"
df_filtered = pd.read_sql(q, conn)
conn.close()
print(df_filtered)

           country  literacy_rate_x
0    United States             99.0
1            China             97.2
2            Japan             99.0
3          Germany             99.0
4   United Kingdom             99.0
5           France             99.0
6            Italy             99.0
7           Canada             99.0
8        Australia             99.0
9           Brazil             93.2
10          Russia             99.7
11     South Korea             98.8
12           Spain             98.6
13          Mexico             95.4
14       Indonesia             96.0
15    Saudi Arabia             97.3
16          Turkey             96.7
17    South Africa             95.0
18       Argentina             99.1
19     Netherlands             99.0
20     Switzerland             99.0
21          Sweden             99.0
22          Norway            100.0
23       Singapore             97.5

#14 Find the Top 5 countries with the highest internet penetration.

In [182]:
internet_penetration = merged_df.sort_values(by='internet_penetration (%)', ascending = False)
internet_penetration.head(5)

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%),gdp_per_capita
21,Switzerland,8654622,8500000,940000,99.0,98.21,0.11
23,Norway,5421241,5300000,580000,100.0,97.76,0.11
16,Saudi Arabia,34813871,34000000,1100000,97.3,97.66,0.03
22,Sweden,10353442,10100000,650000,99.0,97.55,0.06
20,Netherlands,17441139,17000000,1150000,99.0,97.47,0.07

#15 Calculate the total population.

In [184]:
population.isna().mean()

country       0.0
population    0.0
dtype: float64

#16 Find the country with the highest GDP per capita

In [195]:
import sqlite3
conn = sqlite3.connect('country_statistics.db')
q = 'SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 1'
df_filtered_gdp_Per_Capita = pd.read_sql(q, conn)
conn.close()
print(df_filtered_gdp_Per_Capita)
print("\n")

       country  gdp_per_capita
0  Switzerland            0.11

#17 Export the final merged dataset as a CSV file

In [200]:
import sqlite3
conn = sqlite3.connect('country_statistics.db')
final_df = pd.read_sql_query("SELECT * FROM country_statistics", conn)
conn.close()
final_df.to_csv('country_statics.csv', index = False)
print("Dataset exported to 'country_statistics.csv',")
print("\n")

Dataset exported to 'country_statistics.csv',

#18 Sort the dataset in descending order of GDP per Capita and display the Top 10 countries.

Write a short summary (5–6 points) explaining your ETL process, including:

● Data sources used

● Data cleaning steps

● Transformations performed

● Database loading process

● Key insights obtained from the analysis

In [210]:
import sqlite3
conn = sqlite3.connect('country_statistics.db')
q = "SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 10"
df_top10_gdp_Per_capita = pd.read_sql_query(q, conn)
conn.close()
print(df_top10_gdp_Per_capita)
print("\n")

          country  gdp_per_capita
0     Switzerland            0.11
1          Norway            0.11
2       Singapore            0.09
3   United States            0.09
4       Australia            0.07
5     Netherlands            0.07
6         Germany            0.06
7          Canada            0.06
8  United Kingdom            0.06
9          Sweden            0.06